### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by SerGobec** [SerGobec/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Pohrebets** [comment]
Лионель Месси — величайший игрок современного футбола и лучший футболист всех времен. Его упорство, уникальная способность преодолевать защиту соперников и потрясающие финты навсегда останутся в памяти поклонников игры миллионов. За ним закрепились титулы, достижения и звания, но сам Месси утверждает, что индивидуальные награды для него на втором месте, главное — успех команды.
