### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by SerGobec** [SerGobec/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Pohrebets** [comment]
https://www.instagram.com/leomessi/
https://www.facebook.com/LeoMessi
https://twitter.com/messi10stats
http://www.messi.com/
