### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by SerGobec** [SerGobec/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Pohrebets** [comment]
-JUN 24, 1992
Месси начал заниматься футболом в возрасте пяти лет, в местном клубе "Грандоли".на занятия его водила бабушка Селия, единственная из семьи, которая хотела видеть его футболистом.
В возрасте 13 лет Лионель вместе с семьей переехал в Барселону по приглашению клуба " Барселона". Совет директоров согласился оплатить переезд и лечение мальчика (дефицит гормона роста), которое стоило 90 тысяч евро в год. С тех пор он стал выступать за молодежную команду клуба " Барселона".
-NOV 17, 2003
В этот день Месси дебютировал за основной состав, в товарищеской игре против "Порту". Тогда же газета "El Mundo" написала:«У этого паренька левая нога Марадоны, скоростные качества Кройфа и пас Роналдиньо»
-EB 18, 2008
Перед началом нового сезона Лионель Месси сменил свой старый номер 19 на новый 10, который ему достался от ушедшего в итальянский «Милан» Роналдиньо. Месси великолепно провёл весь сезон, выиграв с «Барселоной» три турнира: чемпионат Испании 2008/2009, Кубок Испании и Лигу чемпионов. В чемпионате Испании Месси забил 23 мяча и отдал 12 голевых передач в 31 встрече.
-DEC 1, 2009
Лионель Месси получил «Золотой мяч», набрав 473 очка, и обогнал ближайшего конкурента, Криштиану Роналду на рекордные 240 очков. Месси набрал 473 очка из 480 возможных — 96 журналистов со всего мира практически единогласно признали его лучшим. Он стал первым аргентинцем, который удостоился почётной награды от журнала France Football. Сам Месси сказал, что не ожидал такой уверенной победы.
-AUG 25, 2011
Месси была вручена награда Лучшему игроку года в Европе по версии УЕФА. Первого обладателя этого приза определили 53 журналиста из стран-членов Европейского футбольного союза. Тройку финалистов составили игроки «Барселоны» Хави (11 голосов) и Лионель Месси (39 голосов), а также Криштиану Роналду (3 голоса) из «Реала».
-JAN 9, 2012
В период с 2009-2012 годы Месси стал рекордсменом по количеству "Золотых мячей". Еще никому за всю историю футбола не удавалось получать столько "мячей" подряд.
-OCT 21, 2014
Нападающий «Барселоны» Лионель Месси забил гол и отдал голевую передачу в матче группового этапа Лиги чемпионов с «Аяксом» (3:1). Таким образом, Месси набрал 500 очков по системе «гол+пас» в 436 матчах за каталонский клуб. Отмечу, что всего в этих матчах сине-гранатовые забили 1068 голов. В половине из них Месси поучаствовал, отдавая голевой пас или забивая.
-JAN 11, 2016
11 января 2016 года аргентинец получил пятый в своей карьере «Золотой мяч».
-today
Продолжает быть лучшим в мире <3
