### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by SerGobec** [SerGobec/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Pohrebets** [comment]
Интересные факты
-В интервью Месси признался, что ему не нравится, когда поклонники называют его Богом: «Я с уважением отношусь к подобному, понимая, что люди говорят это без злого умысла, но это преувеличение». К тому же это слышат его дети, а затем повторяют.
-Дома у футболиста есть музей с личными трофеями, где стоят «Золотой мяч ФИФА», «Золотая бутса» и многие другие награды. Он постоянно пополняется новыми экспонатами.
-Лионель считает, что лучшей в карьере была эпоха при Хосепе Гвардиоле. А самый значимый гол забит головой в ворота «МЮ» в финале Лиги чемпионов.
-Про знаменитость был снят документальный фильм «Месси», а также написана книга Гильемом Балаге, которая получила одноименное название.
Все татуировки Месси делает один мастер Роберто Лопес. Первое тату на спине в виде лица матери он нанес в 2010 году. Футболист долго решался на этот шаг и даже интересовался у Дани Алвеса, насколько будет больно. Затем на теле появились изображение руки сына Тьяго, композиция из кинжала, розы и крыльев, мяч и номер, даты рождения супруги и детей.
